# =============================================================================
# Streamlit Secrets Template
# =============================================================================
# Copy this file to 'secrets.toml' in the same directory and fill in your credentials
# WARNING: Never commit secrets.toml to version control!

# =============================================================================
# SNOWFLAKE CONNECTION
# =============================================================================
# Required for: Cortex AI queries, agent chat, and analytics dashboards
# Get your credentials from: https://app.snowflake.com/
[connections.snowflake]
account = "YOUR_ACCOUNT_NAME"              # e.g., "COMPANY_ENTERPRISE"
user = "YOUR_USERNAME"                      # Your Snowflake username
password = "YOUR_PASSWORD_OR_TOKEN"         # Password or authentication token
role = "YOUR_ROLE"                          # e.g., "ACCOUNTADMIN", "SYSADMIN"
warehouse = "YOUR_WAREHOUSE"                # e.g., "COMPUTE_WH"
database = "YOUR_DATABASE"                  # e.g., "ANALYTICS_DB"
schema = "PUBLIC"                           # Default schema to use

# =============================================================================
# POSTGRESQL CONNECTION
# =============================================================================
# Required for: Budget dashboard, transaction management, and data storage
# Can be local PostgreSQL or cloud-hosted (AWS RDS, Azure, etc.)
[postgres]
host = "your-postgres-host.com"             # e.g., "localhost" or "mydb.123456.us-west-2.rds.amazonaws.com"
port = 5432                                 # Default PostgreSQL port
database = "your_database_name"             # Database name
user = "your_username"                      # Database username
password = "your_secure_password"           # Database password
sslmode = "require"                         # SSL mode: "disable", "require", "verify-ca", "verify-full"

# =============================================================================
# SNOWFLAKE CORTEX AGENT
# =============================================================================
# Required for: AI-powered chat interface and financial insights
# Generate PAT (Personal Access Token) in Snowflake: Account > Security > Personal Access Tokens
[agent]
SNOWFLAKE_PAT = "your-personal-access-token"            # Snowflake Personal Access Token
SNOWFLAKE_HOST = "YOUR_ACCOUNT.snowflakecomputing.com" # Full Snowflake host URL

# =============================================================================
# OPENAI API (Optional)
# =============================================================================
# Required for: Semantic search with embeddings in the Search Demo page
# Get your API key from: https://platform.openai.com/api-keys
# Note: Only needed if you want to use pgvector semantic search functionality
[openai]
api_key = "sk-proj-your-openai-api-key-here"           # OpenAI API key (starts with sk-proj- or sk-)

# =============================================================================
# SETUP INSTRUCTIONS
# =============================================================================
# 
# 1. Copy this file:
#    cp .streamlit/secrets_template.toml .streamlit/secrets.toml
# 
# 2. Edit .streamlit/secrets.toml with your actual credentials
# 
# 3. Make sure .streamlit/secrets.toml is in .gitignore (already included)
# 
# 4. Test your connection by running:
#    streamlit run streamlit_app.py
# 
# =============================================================================
# SECURITY NOTES
# =============================================================================
# 
# - Never commit secrets.toml to version control
# - Keep your credentials secure and don't share them
# - Rotate credentials regularly
# - Use environment variables for CI/CD pipelines
# - Consider using a secrets manager for production deployments
# 
# =============================================================================
# MINIMAL SETUP (PostgreSQL only)
# =============================================================================
# 
# If you only want to use the budget dashboard and transaction management:
# - Fill in only the [postgres] section
# - Check "Enable PostgreSQL" in the sidebar
# - Other features will be disabled but core functionality will work
# 
# =============================================================================

